# Generated by Django 4.1.3 on 2023-08-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(null=True, verbose_name='Долгота')),
                ('height', models.IntegerField(null=True, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Координата',
                'verbose_name_plural': 'Координаты',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(blank=True, max_length=255, verbose_name='Название фото 1')),
                ('title_2', models.CharField(blank=True, max_length=255, verbose_name='Название фото 2')),
                ('title_3', models.CharField(blank=True, max_length=255, verbose_name='Название фото 3')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=30, verbose_name='Электронная почта')),
                ('phone', models.CharField(help_text='Формат ввода: +70123456789', max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(blank=True, max_length=255, verbose_name='Префикс')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(blank=True, max_length=255, verbose_name='Другое название')),
                ('connect', models.CharField(blank=True, max_length=255, verbose_name='Соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.images', verbose_name='Изображения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Перевал',
                'verbose_name_plural': 'Перевалы',
            },
        ),
    ]
