# Generated by Django 4.1.3 on 2023-08-13 11:37

from django.db import migrations, models
import pereval.utils


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_1',
            field=models.ImageField(blank=True, max_length=255, upload_to=pereval.utils.get_image_path, verbose_name='Фотография 1'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, upload_to=pereval.utils.get_image_path, verbose_name='Фотография 2'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, upload_to=pereval.utils.get_image_path, verbose_name='Фотография 3'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='level',
            field=models.CharField(choices=[('winter-1A', 'Зима-1А'), ('winter-2A', 'Зима-2А'), ('winter-3A', 'Зима-3А'), ('winter-1B', 'Зима-1Б'), ('winter-2B', 'Зима-2Б'), ('winter-3B', 'Зима-3Б'), ('spring-1A', 'Весна-1А'), ('spring-2A', 'Весна-2А'), ('spring-3A', 'Весна-3А'), ('spring-1B', 'Весна-1Б'), ('spring-2B', 'Весна-2Б'), ('spring-3B', 'Весна-3Б'), ('summer-1A', 'Лето-1А'), ('summer-2A', 'Лето-2А'), ('summer-3A', 'Лето-3А'), ('summer-1B', 'Лето-1Б'), ('summer-2B', 'Лето-2Б'), ('summer-3B', 'Лето-3Б'), ('autumn-1A', 'Осень-1А'), ('autumn-2A', 'Осень-2А'), ('autumn-3A', 'Осень-3А'), ('autumn-1B', 'Осень-1Б'), ('autumn-2B', 'Осень-2Б'), ('autumn-3B', 'Осень-3Б')], default='summer-1B', max_length=9, verbose_name='Категория трудности'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('pending', 'Модератор взял в работу'), ('accepted', 'Модерация прошла успешно'), ('rejected', 'Модерация прошла, информация не принята')], default='new', max_length=8, verbose_name='Статус данных'),
        ),
    ]
